import os, re, imp
Import('env')

if GetOption('win64'):
    from scons import win_build as c
elif GetOption('mac'):
    from scons import mac_build as c
else:
    from scons import linux_build as c
 
c.cppflags.extend(['-O0', '-g','-std=c++1y'])
c.cppflags.extend(['-Wall', '-Wextra'])
 
target   = '#/bin/test' + c.targetSuffix
cppFiles = [Glob('*.cpp') +
            Glob('*/*.cpp')]
 
app = env.Program(target, cppFiles,
                  LIBPATH   = c.libpaths,
                  CPPPATH   = c.sourcepaths,
                  CPPFLAGS  = c.cppflags,
                  LINKFLAGS = c.linkflags,
                  LIBS      = c.libs)
                  
Default(app)
